#.PHONY: all clean
## C compiler and C flags to compile with
#CC=clang
#CFLAGS=-Wall -pedantic
#LIBS=-lm
## convert the other .c files used in TARGET to .o files
#SRCS=path.c move.c person.c
#OBJS=$(SRCS:.c=.o)
## the name of the target executable and .c file
#TARGET=lattice_paths
#
#all: $(TARGET)
#
#$(TARGET): $(OBJS)
#	$(CC) $(CFLAGS) $(LIBS) $(TARGET).c -o $@ $(OBJS)
#
#%.o: %.c
#	$(CC) $(CFLAGS) $(LIBS) -c $< -o $@
#
#clean:
#	rm -- $(OBJS) $(TARGET)
